spring:
  application:
    name: inter-hub-lms-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lms-service-db
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: schema_lms
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: schema_lms
    enabled: true

snowflake:
  worker-id: 10
  datacenter-id: 10