spring:
  application:
    name: inter-hub-lms-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: schema_lms
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: schema_lms
    enabled: true

aws:
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION}
    end-point: ${S3_ENDPOINT}
    bucket-name: ${S3_BUCKET_NAME}
    paths:
      lesson: lessons/
      course: courses/
      submission: submissions/
    max-file-size: 20971520
    allow-types:
      image: "image/(png|jpeg|jpg)"
      document: "application/(pdf|msword|vnd.openxmlformats-officedocument.wordprocessingml.document|vnd.ms-excel|vnd.openxmlformats-officedocument.spreadsheetml.sheet)|image/(png|jpeg|jpg)"

snowflake:
  worker-id: 10
  datacenter-id: 10